### ISSUE TITLE
Action to construct arn if not available in alert json

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#126]
Vendors like Prisma Cloud do not give us access to the arn of a resource. In order for our actions and other workflows to function as expected we need to have access to the AWS arn. In order to get the arn, we must construct it according to how AWS expects it.

For s3 (note there is no resource type):
```
arn:${Partition}:s3:::${BucketName}	
```

For EC2 -> instance:
```
arn:${Partition}:ec2:${Region}:${Account}:instance/${InstanceId}	
```

For EC2 -> security-group:
```
arn:${Partition}:ec2:${Region}:${Account}:security-group/${SecurityGroupId}	
```

For IAM -> policy:
```
arn:${Partition}:iam::${Account}:policy/${PolicyNameWithPath}	
```

For IAM -> user:
```
arn:${Partition}:iam::${Account}:user/${UserNameWithPath}	
```

All of the arns that I have listed in this ticket are from here: https://awspolicygen.s3.amazonaws.com/js/policies.js

More info about arns can be found here as well:
https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html

**Comment by gauravphoenix** [comment]
Based on internal discussions, we have decided not to proceed with this
