### ISSUE TITLE
Update arn constructor action to be able to work with any arn

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#129]
AWS has done a good job of listing all possible arns here: https://awspolicygen.s3.amazonaws.com/js/policies.js

We need to extract all the arns. Then when we get the input during normalization of all values except canonical ID, we should find the appropriate arn, input the appropriate variables and construct a canonical id as per AWS' requirements.

**Comment by gauravphoenix** [comment]
this action will be helpful with the vendors which do not emit arn in the their alerts.

**Comment by gauravphoenix** [comment]
Based on internal discussion, we have decided not to proceed with this
