### ISSUE TITLE
Add class and subclass to AWS SecurityHub user defined fields

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#171]
For SecurityHub alerts, we add some custom fields to make it easy for our users to filter findings based on Dassana's insights. Currently, we add policy category and subcategory however we don't add class and subclass since they were new introductions. Please add these two fields in the findings.

Also please rename the keys to not have the term `POLICY_CONTEXT`. Rather you should replace this term with `ALERT`. For example: `DASSANA_ALERT_CLASS`.

**Comment by hk-dassana** [comment]
code has been rolled out on 09/30/21.
