### ISSUE TITLE
Autogen Azure + GCP Policies

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#259]
Only generate a list of all the policies without the mapping. We will take care of mapping later on once we have the resource hierarchy in place.

**Comment by dassana-junix** [comment]
find . -name "*.json" -print0 | xargs -0 jq '{"Name" : .name , "Description" : .description, "Category" : "", "Subcategory" : "", "Service" : "", "Resource Type" : "", "cloudType" : .cloudType, "severity" : .severity, "policyId": .policyId, "searchModel.query" : .["searchModel.query"]}' | jq -r -s '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.]|tostring)) as $rows | $cols, $rows[]| @csv' > policies.csv
