### ISSUE TITLE
support skipping resource and policy context 

### ISSUE THREAD

**Issue by gauravphoenix** [dassana-io/dassana#270]
Given that normalization itself is quite powerful, there are cases where we want to run only normalization and no resource and policy contextualization. For example, it may be possible, for some alert vendors, that we can run normalization without requiring any access to CSP. Let's call such alert vendors as standalone vendors. For these standalone vendors, it will be great to have an option to just do normalization and don't run any other workflows. 

This is in the spirit of best effort basis processing.

**Comment by parth-dassana** [comment]
Will not be doing this anymore as we are supporting graceful error handling.
